ALTER TABLE `DBNAMEmenu` ADD CONSTRAINT `menu_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEpage` ADD CONSTRAINT `page_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEuser` ADD CONSTRAINT `avatar` FOREIGN KEY (`avatar`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEimage` ADD CONSTRAINT `image_user` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEproduct` ADD CONSTRAINT `product_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEproduct` ADD CONSTRAINT `menu_product` FOREIGN KEY (`menu_id`) REFERENCES `DBNAMEmenu` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEaddress` ADD CONSTRAINT `user_address` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `DBNAMEorder` ADD CONSTRAINT `user_order` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
