ALTER TABLE `DBNAMEmenu` DROP FOREIGN KEY `image`;
ALTER TABLE `DBNAMEmenu` ADD CONSTRAINT `menu_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEpage` DROP FOREIGN KEY `image`;
ALTER TABLE `DBNAMEpage` ADD CONSTRAINT `page_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEuser` DROP FOREIGN KEY `avatar`;
ALTER TABLE `DBNAMEuser` ADD CONSTRAINT `avatar` FOREIGN KEY (`avatar`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEimage` DROP FOREIGN KEY `user_id`;
ALTER TABLE `DBNAMEimage` ADD CONSTRAINT `image_user` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEproduct` DROP FOREIGN KEY `image`;
ALTER TABLE `DBNAMEproduct` ADD CONSTRAINT `product_image` FOREIGN KEY (`image`) REFERENCES `DBNAMEimage` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEproduct` DROP FOREIGN KEY `menu_id`;
ALTER TABLE `DBNAMEproduct` ADD CONSTRAINT `menu_product` FOREIGN KEY (`menu_id`) REFERENCES `DBNAMEmenu` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEaddress` DROP FOREIGN KEY `user_id`;
ALTER TABLE `DBNAMEaddress` ADD CONSTRAINT `user_address` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEorder` DROP FOREIGN KEY `user_id`;
ALTER TABLE `DBNAMEorder` ADD CONSTRAINT `user_order` FOREIGN KEY (`user_id`) REFERENCES `DBNAMEuser` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEproduct_order` DROP FOREIGN KEY `order_id`;
ALTER TABLE `DBNAMEproduct_order` ADD CONSTRAINT `order_id` FOREIGN KEY (`order_id`) REFERENCES `DBNAMEorder`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE `DBNAMEproduct_order` DROP FOREIGN KEY `product_id`;
ALTER TABLE `DBNAMEproduct_order` ADD CONSTRAINT `product_id` FOREIGN KEY (`product_id`) REFERENCES `DBNAMEproduct`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
