# MainController Routes
/:
  controller: MainController
  action: home
  access: guest;user;admin

/404:
  controller: MainController
  action: notFound
  access: guest;user;admin

# SecurityController Routes
/register:
  controller: SecurityController
  action: register
  access: guest

/login:
  controller: SecurityController
  action: login
  access: guest

/forgot-password:
  controller: SecurityController
  action: resetPassword
  access: guest

/logout:
  controller: SecurityController
  action: logout
  access: user;admin

# AdminController Routes
/admin:
  controller: AdminController
  action: default
  access: admin

# MenuController Routes
/admin/menus:
  controller: MenuController
  action: default
  access: admin

/admin/menus/edit:
  controller: MenuController
  action: editMenu
  access: admin

/admin/menus/delete:
  controller: MenuController
  action: deleteMenu
  access: admin

# ProductController Routes
/admin/products:
  controller: ProductController
  action: default
  access: admin

/admin/products/new:
  controller: ProductController
  action: newProduct
  access: admin

/admin/products/edit:
  controller: ProductController
  action: editProduct
  access: admin

/admin/products/delete:
  controller: ProductController
  action: deleteProduct
  access: admin

# PageController Routes
/admin/pages:
  controller: PageController
  action: pages
  access: admin

/admin/pages/new:
  controller: PageController
  action: newPage
  access: admin

/admin/page:
  controller: PageController
  action: editPage
  access: admin
