/:
  controller: Main
  action: default

/admin:
  controller: Security
  action: default

/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout