# MainController routes
/:
  controller: MainController
  action: home
  access: guest;user;admin

/404:
  controller: MainController
  action: notFound
  access: guest;user;admin

# Setup Page
/setup:
  controller: SetupController
  action: default
  access: guest

# SecurityController routes
/register:
  controller: SecurityController
  action: register
  access: guest

/login:
  controller: SecurityController
  action: login
  access: guest

/logout:
  controller: SecurityController
  action: logout
  access: user;admin

/forgot-password:
  controller: SecurityController
  action: resetPassword
  access: guest

/profile:
  controller: SecurityController
  action: profile
  access: user

# AdminController routes
/admin:
  controller: AdminController
  action: main
  access: admin

/admin/profile:
  controller: SecurityController
  action: profile
  access: admin

# MenuController routes
/admin/menus:
  controller: MenuController
  action: main
  access: admin

/admin/menu/new:
  controller: MenuController
  action: newMenu
  access: admin

/admin/menu:
  controller: MenuController
  action: editMenu
  access: admin

/menu:
  controller: MenuController
  action: show
  access: guest;user;admin

# ProductController routes
/admin/products:
  controller: ProductController
  action: main
  access: admin

/admin/product/new:
  controller: ProductController
  action: newProduct
  access: admin

/admin/product:
  controller: ProductController
  action: editProduct
  access: admin

/product:
  controller: PageController
  action: show
  access: guest;user;admin

/products:
  controller: PageController
  action: products
  access: guest;user;admin

# PageController routes
/admin/pages:
  controller: PageController
  action: main
  access: admin

/admin/page/new:
  controller: PageController
  action: newPage
  access: admin

/admin/page:
  controller: PageController
  action: editPage
  access: admin

/page:
  controller: PageController
  action: show
  access: guest;user;admin

# OrderController routes
/admin/orders:
  controller: OrderController
  action: main
  access: admin

/order:
  controller: OrderController
  action: newOrder
  access: user;admin

# UserController routes
/admin/users:
  controller: UserController
  action: main
  access: admin

/admin/user/new:
  controller: UserController
  action: newUser
  access: admin

/admin/user:
  controller: UserController
  action: editUser
  access: admin